// Mocks generated by Mockito 5.4.4 from annotations
// in send_money_app/test/presentation/cubit/send_money_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:send_money_app/core/error/failures.dart' as _i7;
import 'package:send_money_app/domain/entities/transaction.dart' as _i8;
import 'package:send_money_app/domain/repositories/transaction_repository.dart'
    as _i2;
import 'package:send_money_app/domain/usecases/send_money.dart' as _i5;
import 'package:send_money_app/presentation/cubit/home/home_cubit.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTransactionRepository_0 extends _i1.SmartFake
    implements _i2.TransactionRepository {
  _FakeTransactionRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeState_2 extends _i1.SmartFake implements _i4.HomeState {
  _FakeHomeState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SendMoney].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendMoney extends _i1.Mock implements _i5.SendMoney {
  MockSendMoney() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TransactionRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTransactionRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TransactionRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.Transaction>> call(double? amount) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [amount],
        ),
        returnValue: _i6.Future<_i3.Either<_i7.Failure, _i8.Transaction>>.value(
            _FakeEither_1<_i7.Failure, _i8.Transaction>(
          this,
          Invocation.method(
            #call,
            [amount],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, _i8.Transaction>>);
}

/// A class which mocks [HomeCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeCubit extends _i1.Mock implements _i4.HomeCubit {
  MockHomeCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.HomeState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeHomeState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.HomeState);

  @override
  _i6.Stream<_i4.HomeState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i6.Stream<_i4.HomeState>.empty(),
      ) as _i6.Stream<_i4.HomeState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void toggleBalanceVisibility() => super.noSuchMethod(
        Invocation.method(
          #toggleBalanceVisibility,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateBalance(double? newBalance) => super.noSuchMethod(
        Invocation.method(
          #updateBalance,
          [newBalance],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.HomeState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i9.Change<_i4.HomeState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
